name: Update selected tools
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 1/5 * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31.8.4
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            accept-flake-config = true
      - run: nix flake update unstable-small nix-ai-tools
      - uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PAT_FOR_PR }}
          title: 'chore: Update tools'
          branch: bot/update/ai-tools
          labels: automation,update
